### ISSUE TITLE
Allow checks to be overriden by config

### ISSUE THREAD

**Issue by swiedernix** [xoxys/ansible-later#27]
It'd be great if we can configure ansible-later to override some check results, for example command usage triggers ANSIBLE0011 as an error. But we'd like to treat that as an warning instead.

**Comment by xoxys** [comment]
That's already possible. Edit your `standards.py` file to this or simply remove the standard `version=` from the file instead of commenting.

```
commands_should_be_idempotent = Standard(dict(
    id="ANSIBLE0011",
    name="Commands should be idempotent",
    check=check_command_has_changes,
#    version="0.1",
    types=["playbook", "task"]
))
```

If a standard not defines a version, it will be no longer mandatory. As I remember correctly you're managing your `standards.py` in a separate git repo ;)

**Comment by xoxys** [comment]
Feel free to reopen the issue if you missed something.
