### ISSUE TITLE
[ANSIBLE0001] check on newer Cisco Modules

### ISSUE THREAD

**Issue by tweippert** [xoxys/ansible-later#30]
Newer Cisco IOS/IOSXR/NX-OS use a config syntax which triggers ANSIBLE0001:

- name: Configure Access Port (General)
  ios_interfaces:
    config:
      - name: "FastEthernet0/1"
        description: "Port 1"
        enabled: "true"
    state: merged

results in:

ERROR: [ANSIBLE0001] Standard 'Single tasks should be separated by empty line' not met:
... tasks/ios_ports.yml:10: missing task separation (required: 1 empty line)

It seems the Config syntax with the "-" triggers a false-positive!?

Will look into it, if i can fix it myself, but hadn't needed time.

**Comment by xoxys** [comment]
@tweippert Should be fixed in the latest docker image. Could you verify after CI has released the updated image?

**Comment by tweippert** [comment]
Checked it against the git version and it looks good. Seems to fix my issue :) 
Thanks for the quick response!

**Comment by xoxys** [comment]
Cool. Feel free to re-open the issue if you find some missing cases :)
