### ISSUE TITLE
Add an exception for ANSIBLE0010

### ISSUE THREAD

**Issue by tboerger** [xoxys/ansible-later#34]
Generally the check is totally fine, but it should contain an exception, if the task contains an `args.executable` attribute this check should not be triggered as `args.executable` is not available within Ansible since v2.4.

**Comment by xoxys** [comment]
Thanks for reporting. Addressed by https://github.com/xoxys/ansible-later/commit/8cc9583949d3d352b05041bee620612455dafbcd
